@hostname = localhost
@port = 3000
@host = {{hostname}}:{{port}}
@baseURL = http://{{host}}/api
@sessionID =

### Logout
POST {{baseURL}}/users/logout HTTP/1.1

### Upgrade Role Request Token
GET {{baseURL}}/users/upgrade-role HTTP/1.1

### Me
GET {{baseURL}}/users/me HTTP/1.1

